import './globals.css';
import { AuthContext } from '@/context/AuthContext';
import Navbar from '@/components/Navbar';


const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <AuthContext>
        <Navbar />
        <body>{children}</body>
      </AuthContext>
    </html>
  );
}
